// <auto-generated />
using AirportTask.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirportTask.Model.Runway19", b =>
                {
                    b.Property<string>("AirportIcaoIdentifier")
                        .HasColumnType("char(4)");

                    b.Property<string>("ContinuationNumber")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("CustomerAreaCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplacedThresholdDistance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcaoCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("LocalizerCatClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizerRefIdent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LtpEllipsoidHeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("RunwayDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayGradient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayLatitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayLength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayLongitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayMagneticBearing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayWidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLocalizerCatClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLocalizerRefIdent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Stopway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSectionCode")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("TchValueIndicator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThresholdCrossingHeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportIcaoIdentifier");

                    b.ToTable("Runway19");
                });

            modelBuilder.Entity("AirportTask.Model.Runway22", b =>
                {
                    b.Property<string>("AirportIcaoIdentifier")
                        .HasColumnType("char(4)");

                    b.Property<string>("ContinuationNumber")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("CustomerAreaCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplacedThresholdDistance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcaoCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("LocalizerCatClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizerRefIdent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LtpEllipsoidHeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("RunwayDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayGradient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayLatitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayLength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayLongitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayMagneticBearing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayWidth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLocalizerCatClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLocalizerRefIdent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Stopway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSectionCode")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("TchValueIndicator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThresholdCrossingHeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportIcaoIdentifier");

                    b.ToTable("Runway22");
                });
#pragma warning restore 612, 618
        }
    }
}
